[package]
name = "csi-server"
version.workspace = true
edition.workspace = true

build = "build.rs"

[dependencies]
csi-core.workspace = true
csi-analysis.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
axum.workspace = true
tokio.workspace = true
rust-embed.workspace = true
mime_guess.workspace = true
